using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace CSDLPT
{
    public partial class MainForm : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public MainForm()
        {
            InitializeComponent();
            loadInit();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        public void loadInit()
        {
            String phanQuyen = "";
            switch (Program.mGroup)
            {
                case "COSO":
                    {
                        phanQuyen = "Cơ Sở";
                        btnThi.Enabled = false;
                        break;
                    }
                case "GIANGVIEN":
                    {
                        phanQuyen = "Giáo viên";
                        btnGiangVien.Enabled = btnMonhoc.Enabled = btnThi.Enabled = true;
                        break;
                    }
                case "TRUONG":
                    {
                        phanQuyen = "Trường";
                        btnGiangVien.Enabled = btnMonhoc.Enabled = true;
                        btnThi.Enabled = false;
                        break;
                    }
                default: {
                        phanQuyen = "Sinh viên";
                        btnGiangVien.Enabled = btnMonhoc.Enabled = false;
                        btnThi.Enabled = true;
                        break;
                    }
            }
            lbGroup.Text = "Group: " + phanQuyen +"\nHọ Tên: "+ Program.mHoten;

        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
            DangNhap dn = new DangNhap();
            dn.Show();
        }

        private void bindingSource1_CurrentChanged(object sender, EventArgs e)
        {

        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form frm = this.CheckExists(typeof(FrmMonHoc));
            if (frm != null) frm.Activate();
            else
            {
                FrmMonHoc f = new FrmMonHoc();
                f.MdiParent = this;
                f.Show();
            }
        }

        private Form CheckExists(Type ftype)
        {
            foreach (Form f in this.MdiChildren)
                if (f.GetType() == ftype)
                    return f;
            return null;
        }

        private void barButtonItem1_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form frm = this.CheckExists(typeof(FrmGiangVien));
            if (frm != null) frm.Activate();
            else
            {
                FrmGiangVien f = new FrmGiangVien();
                f.MdiParent = this;
                f.Show();
            }
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form frm = this.CheckExists(typeof(FrmTaoTaiKhoan));
            if (frm != null) frm.Activate();
            else
            {
                FrmTaoTaiKhoan f = new FrmTaoTaiKhoan();
                f.MdiParent = this;
                f.Show();
            }
        }

        private void barButtonItem4_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form frm = this.CheckExists(typeof(FrmThi));
            if (frm != null) frm.Activate();
            else
            {
                FrmThi f = new FrmThi();
                f.MdiParent = this;
                f.Show();
            }
        }

        private void btnDangKi_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form frmDK = this.CheckExists(typeof(FrmGVDangKy));
            if (frmDK != null) frmDK.Activate();
            else
            {
                FrmGVDangKy f = new FrmGVDangKy();
                f.MdiParent = this;
                f.Show();
            }
        }

        private void btnRpDSDKThi_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form frmDK = this.CheckExists(typeof(FrmDSDK));
            if (frmDK != null) frmDK.Activate();
            else
            {
                FrmDSDK f = new FrmDSDK();
                f.MdiParent = this;
                f.Show();
            }
        }

        private void barButtonItem2_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form frmDK = this.CheckExists(typeof(FrmBoDe));
            if (frmDK != null) frmDK.Activate();
            else
            {
                FrmBoDe f = new FrmBoDe();
                f.MdiParent = this;
                f.Show();
            }
        }

        private void btnBangDiem_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form frmBanđiem = this.CheckExists(typeof(FrmBangDiem));
            if (frmBanđiem != null) frmBanđiem.Activate();
            else
            {
                FrmBangDiem f = new FrmBangDiem();
                f.MdiParent = this;
                f.Show();
            }
        }

        private void btnKhoa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form frmKhoa = this.CheckExists(typeof(FrmKhoa));
            if (frmKhoa != null) frmKhoa.Activate();
            else
            {
                FrmKhoa f = new FrmKhoa();
                f.MdiParent = this;
                f.Show();
            }
        }

        private void btnTraCuu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form frmTraCuu = this.CheckExists(typeof(FrmTraCuu));
            if (frmTraCuu != null) frmTraCuu.Activate();
            else
            {
                FrmTraCuu f = new FrmTraCuu();
                f.MdiParent = this;
                f.Show();
            }
        }

        private void barButtonItem1_ItemClick_2(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }
    }
}
